[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 88

[tool.ruff]
line-length = 88
target-version = "py311"
extend-exclude = [
    ".bmad-core",
    "artifacts",
    "htmlcov",
    "__pycache__",
]

[tool.ruff.lint]
select = ["E", "W", "F"]
ignore = ["E501"]  # Let Black own line length

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["E402"]
"scripts/**" = ["E402", "F401", "F541", "F841", "E722"]
"test_*.py" = ["E402", "E722"]
"*_test.py" = ["E402", "E722"]
"run_validation.py" = ["E402"]
"security/**" = ["E722"]
"termnet/**" = ["E722", "E402"]
"artifacts/**" = ["E722", "E402", "E501"]
".bmad-core/**" = ["E722", "E402", "E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
