name: TermNet CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.python-version }}-
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pre-commit hooks
      run: |
        pip install pre-commit
        # First run to catch and fix any issues
        if ! pre-commit run --all-files; then
          echo "Pre-commit hooks made changes. Checking if repository is now clean..."
          # Add any changes made by pre-commit hooks
          git add -A
          # Check if there are still changes to commit
          if [ -n "$(git status --porcelain)" ]; then
            echo "❌ Repository has uncommitted changes after pre-commit formatting:"
            git status --porcelain
            echo ""
            echo "These files need to be committed with their formatting changes."
            echo "Please run 'pre-commit run --all-files' locally and commit the changes."
            exit 1
          else
            echo "✅ Repository is clean after pre-commit formatting"
          fi
        else
          echo "✅ All pre-commit hooks passed without making changes"
        fi

    - name: Test with pytest
      run: |
        pytest -q --tb=short

    - name: Upload coverage as artifact
      if: matrix.python-version == '3.12'  # Only upload once
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: .coverage
        if-no-files-found: ignore
        retention-days: 30
