name: TermNet CI

on:
  pull_request:
  push:
    branches: [main, feat/**]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # pin for stability

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pre-commit pytest pytest-asyncio anyio

      - name: Lint (changed files only; fallback)
        run: |
          CHANGED=$(git fetch origin main >/dev/null 2>&1 || true; \
            git diff --name-only origin/main...HEAD | grep -E '\.py$' || true)
          if [ -n "$CHANGED" ]; then
            echo "Linting changed files: $CHANGED"
            echo "$CHANGED" | tr '\n' ' ' | xargs python -m flake8
          else
            echo "No changed files detected; linting prod dirs"
            python -m flake8 termnet/termnet/ tests/ scripts/
          fi

  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}   # make imports work
      TERMNET_LEGACY_SAFETY: "1"            # keeps legacy tests happy
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio anyio

      - name: Run tests
        run: python -m pytest -q