name: TermNet CI

on:
  pull_request:
  push:
    branches: [main, feat/**]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # pin for stability

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pre-commit pytest pytest-asyncio anyio

      - name: Write flake8 config
        run: |
          cat > .flake8 <<'EOF'
          [flake8]
          max-line-length = 100
          extend-ignore = W503,E127
          exclude =
              .git,
              __pycache__,
              .venv,
              .bmad-core/,
              artifacts/,
              sync/
          EOF

      - name: Lint (flake8)
        run: python -m flake8

  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}   # make imports work
      TERMNET_LEGACY_SAFETY: "1"            # keeps legacy tests happy
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio anyio

      - name: Run tests
        run: python -m pytest -q